Repository octokit/webhooks.js, pull requests merged in 2020-05, with the labels that each got.

#134 Fix intellisense broken for named import
  README.md
  index.d.ts
  package-lock.json
  package.json
  scripts/generate-types.js
  src/index.js
  test/integration/deprecations-test.js
  test/integration/server-test.js
  test/integration/smoke-test.js
Labels: bug

#137 🐛 fix(declaration-type): fix missing return type on createWebhooksApi
  index.d.ts
  scripts/generate-types.js
  test/typescript-validate.ts
Labels: bug, typescript

#139 💚 ci(test): add typescript validation as a step in Test workflow in CI
  .github/workflows/test.yml
Labels: maintenance, typescript

#142 Replace Greenkeeper with Dependabot
  .github/dependabot.yml
  .github/workflows/test.yml
  .github/workflows/update-prettier.yml
  .github/workflows/update.yml
  README.md
Labels: maintenance

#141 fix(intellisesne): intellisense for array arg in `on`
  index.d.ts
  scripts/generate-types.js
  test/typescript-validate.ts
Labels: bug, typescript
