Repository octokit/webhooks.js, pull requests merged in 2020-12, with the labels that each got.

#370 fix(typescript): add types for check_run.requested_action
  package-lock.json
  package.json
  src/generated/event-payloads.ts
Labels: bug, typescript

#371 ci(update): act on `octokit/webhooks release` dispatch event instead of waiting for dependabot
  .github/workflows/update.yml
Labels: maintenance

#375 chore: update `ts-jest` config
  package.json
Labels: maintenance

#374 refactor(typescript): use `ts-expect-error` instead of `ts-ignore`
  src/event-handler/receive.ts
  src/middleware/get-payload.ts
  src/sign/index.ts
  test/integration/server-test.ts
  test/integration/sign-test.ts
  test/unit/event-handler-on-test.ts
  test/unit/event-handler-receive-test.ts
Labels: maintenance, typescript

#373 fix(typescript): mark `verify` parameters as required
  src/index.ts
  src/middleware/verify-and-receive.ts
  src/verify/README.md
  src/verify/index.ts
  test/integration/verify-test.ts
Labels: bug, typescript

#377 feat(typescript): type `algorithm` property for `sign` options
  src/sign/index.ts
  test/integration/sign-test.ts
Labels: feature, typescript

#372 fix(typescript): export `EventTypesPayload` type
  src/index.ts
Labels: feature, typescript

#380 fix: move `@pika/plugin-ts-standard-pkg` to `devDependencies`
  package-lock.json
  package.json
Labels: bug

#387 fix(typescript): `eventPayload` parameter for `verify()` can be `string`
  src/verify/index.ts
Labels: bug, typescript

#388 fix(typescript): `eventPayload` parameter for `Webhooks#verify` can be `string`
  src/index.ts
Labels: bug, typescript

#392 feat(typescript): type `action` property on payloads
  scripts/generate-types.js
  src/generated/event-payloads.ts
Labels: feature, typescript

#397 feat(typescript): deduplicate `Sender` type
  scripts/generate-types.js
  src/generated/event-payloads.ts
Labels: feature, typescript

#401 Add failing test to verify that "request.setEncoding("utf8")" is needed
  test/integration/middleware-test.ts
Labels: maintenance

#400 docs: Add documentation for the onAny and onError methods
  README.md
Labels: bug, documentation
