Repository octokit/webhooks.js, pull requests merged in 2020-08, with the labels that each got.

#177 test: return type from `options.transform` should be used for `event` type in event handler
  src/event-handler/index.ts
  src/index.ts
  src/middleware/index.ts
  src/types.ts
  test/typescript-validate.ts
Labels: feature, help wanted, typescript

#183 feat: set common error types from Octokit request errors
  package-lock.json
  package.json
  scripts/generate-types.js
  src/event-handler/receive.ts
  src/generated/get-webhook-payload-type-from-event.ts
  src/index.ts
  src/types.ts
  test/integration/event-handler-test.js
  test/typescript-validate.ts
  tsconfig.json
Labels: feature

#189 fix: assure that errors are always instances of AggregateError
  src/event-handler/receive.ts
  src/middleware/get-payload.ts
  src/middleware/middleware.ts
  test/integration/middleware-test.js
Labels: bug

#193 fix(typescript): Remove file extension from import
  src/event-handler/on.ts
Labels: maintenance, typescript

#192 fix(typescript): Change options to match the ones from other octokit repos
  tsconfig.json
Labels: maintenance, typescript

#197 test(middlewares): fix typing of unit test for middlewares
  test/unit/middleware-test.ts
Labels: maintenance, typescript

#195 🚨 test(event-handler-test): add missing done() callback to make async test to wait until all expect
  test/integration/event-handler-test.ts
Labels: maintenance

#200 build(typescript): target to es2020 in tsconfig.json
  tsconfig.json
Labels: feature, typescript

#202 fix: set encoding before reading payload for signature verification
  src/middleware/get-payload.ts
  test/integration/middleware-test.js
Labels: feature

#190 feat: reply after 9s with 202 status
  package-lock.json
  package.json
  src/middleware/middleware.ts
  test/integration/server-test.js
Labels: feature

#204 feat(typescript): export `WebhookError`
  src/event-handler/receive.ts
  src/index.ts
  src/middleware/middleware.ts
  src/types.ts
  test/typescript-validate.ts
Labels: feature, typescript

#236 fix(deps): Depend on aggregate-error 3.1.0
  package.json
Labels: bug, dependencies

#237 fix(sign): make sign() parameters non-optional
  src/sign/index.ts
  test/integration/sign-test.ts
Labels: maintenance, typescript

#238 test(server-test): refactor mock setTimeout using Jest's utility
  package-lock.json
  package.json
  test/integration/server-test.ts
Labels: maintenance

#240 build(pretest): remove 'build' step from pretest stage
  package.json
Labels: maintenance
