Repository octokit/webhooks.js, pull requests merged in 2020-10, with the labels that each got.

#284 refactor(generate-types): add missing DO-NOT-EDIT comment to remaining generated type files
  scripts/generate-types.js
  scripts/update-known-events.js
  src/generated/event-names.ts
  src/generated/event-payloads.ts
  src/generated/get-webhook-payload-type-from-event.ts
  src/generated/webhook-names.ts
Labels: maintenance

#285 refactor(middleware): remove unused import
  src/middleware/middleware.ts
Labels: maintenance

#283 test(ts-validate): event prop in WebhookError is a deprecated prop
  test/typescript-validate.ts
Labels: maintenance

#286 refactor(types.ts): allow handler functions to return any
  src/index.ts
  src/types.ts
  test/typescript-validate.ts
Labels: bug, typescript

#288 build(typescript): add noUnusedLocals and noUnusedParameters to tsconfig.json
  test/integration/event-handler-test.ts
  test/integration/middleware-test.ts
  tsconfig.json
Labels: maintenance, typescript

#290 build(tsconfig): use @octokit/tsconfig preset in local tsconfig.json
  package-lock.json
  package.json
  tsconfig.json
Labels: maintenance, typescript

#291 refactor: remove unreachable code in receive
  src/event-handler/receive.ts
  test/unit/event-handler-receive-test.ts
Labels: maintenance

#292 fix: typescript autocomplete and types for public api
  scripts/generate-types.js
  src/event-handler/on.ts
  src/event-handler/receive.ts
  src/generated/event-names.ts
  src/generated/get-webhook-payload-type-from-event.ts
  src/index.ts
  src/middleware/get-payload.ts
  src/middleware/middleware.ts
  src/types.ts
  test/typescript-validate.ts
Labels: bug, typescript

#309 docs(issue-templates): add issue templates to repository
  .github/ISSUE_TEMPLATE/01_help.md
  .github/ISSUE_TEMPLATE/02_bug.md
  .github/ISSUE_TEMPLATE/03_feature_request.md
  .github/ISSUE_TEMPLATE/04_thanks.md
  .github/ISSUE_TEMPLATE/05_type_pyaloads_incorrect_or_incomplete.md
Labels: maintenance

#318 docs(issue-templates): resort issue-templates to give more visibility to type-payloads one
  .github/ISSUE_TEMPLATE/02_type_pyaloads_incorrect_or_incomplete.md
  .github/ISSUE_TEMPLATE/03_bug.md
  .github/ISSUE_TEMPLATE/04_feature_request.md
  .github/ISSUE_TEMPLATE/05_thanks.md
Labels: maintenance

#319 docs(ISSUE_TEMPLATE): correct package name in Thanks template
  .github/ISSUE_TEMPLATE/05_thanks.md
Labels: maintenance

#321 feature: export `WebhooksEvents` from @octokit/webhooks.js
  scripts/generate-types.js
  src/event-handler/on.ts
  src/event-handler/receive.ts
  src/generated/get-webhook-payload-type-from-event.ts
  src/index.ts
  src/middleware/middleware.ts
  src/types.ts
  test/typescript-validate.ts
Labels: feature, typescript

#322 feat(sign): support sha256 algorithm
  src/middleware/middleware.ts
  src/sign/README.md
  src/sign/index.ts
  src/verify/index.ts
  test/integration/server-test.ts
  test/integration/sign-test.ts
  test/integration/verify-test.ts
  test/typescript-validate.ts
Labels: feature

#324 feat: Add onAny and onEvent functions
  src/event-handler/index.ts
  src/event-handler/on.ts
  src/index.ts
  test/integration/event-handler-test.ts
  test/integration/server-test.ts
  test/typescript-validate.ts
  test/unit/event-handler-on-test.ts
Labels: feature

#339 fix: prefix error messages with "[@octokit/webhooks] "
  src/index.ts
  src/middleware/index.ts
  src/middleware/middleware.ts
  src/middleware/verify-and-receive.ts
  src/verify/index.ts
Labels: bug
