Repository octokit/webhooks.js, pull requests merged in 2021-03, with the labels that each got.

#464 fix(typescript): HandlerFunction argument
  src/event-handler/index.ts
  src/index.ts
  src/types.ts
  test/integration/event-handler-test.ts
  test/typescript-validate.ts
Labels: bug, typescript

#485 Explicitly specify that TS 4.1 is required
  package.json
Labels: maintenance, typescript

#494 fix(typescript): revert #459 & #464
  src/event-handler/index.ts
  src/index.ts
  src/types.ts
  test/integration/event-handler-test.ts
  test/typescript-validate.ts
Labels: bug

#442 test(typescript): add case ensuring action differences are typed
  test/typescript-validate.ts
Labels: maintenance

#511 feat: deprecate `createWebhooksApi()`
  src/index.ts
  test/typescript-validate.ts
  test/unit/deprecation.test.ts
Labels: feature

#514 fix(typescript): default `TTransformed` in `Webhooks` type parameter to `unknown`
  src/index.ts
Labels: bug, typescript

#509 feat: `createNodeMiddleware()`
  README.md
  package-lock.json
  package.json
  src/createLogger.ts
  src/index.ts
  src/middleware-legacy/README.md
  src/middleware-legacy/get-missing-headers.ts
  src/middleware-legacy/get-payload.ts
  src/middleware-legacy/index.ts
  src/middleware-legacy/isnt-webhook.ts
  src/middleware-legacy/middleware.ts
  src/middleware-legacy/verify-and-receive.ts
  src/middleware/node/get-missing-headers.ts
  src/middleware/node/get-payload.ts
  src/middleware/node/index.ts
  src/middleware/node/middleware.ts
  src/middleware/node/on-unhandled-request-default.ts
  src/middleware/node/types.ts
  src/verify/index.ts
  test/integration/middleware-test.ts
  test/integration/node-middleware.test.ts
  test/integration/server-test.ts
  test/unit/deprecation.test.ts
  test/unit/middleware-constructor-test.ts
  test/unit/middleware-test.ts
Labels: feature

#502 ci: update PR body text to reflect npm package name
  .github/workflows/update.yml
Labels: maintenance

#453 docs: document <event>.<action> where applicable
  README.md
Labels: documentation, feature

#461 feat(typescript): compile-time missing secret error
  src/index.ts
  src/middleware-legacy/index.ts
  src/middleware-legacy/middleware.ts
  src/middleware-legacy/verify-and-receive.ts
  test/unit/middleware-constructor-test.ts
  test/unit/middleware-test.ts
Labels: feature
