Repository octokit/webhooks.js, pull requests merged in 2021-02, with the labels that each got.

#417 chore: move `jest` config into `jest.config.ts`
  jest.config.ts
  package-lock.json
  package.json
Labels: maintenance

#406 feat: use new types from `@octokit/webhooks-definitions`
  .github/workflows/update.yml
  README.md
  package-lock.json
  package.json
  scripts/generate-file.js
  scripts/generate-types.js
  scripts/generate-types.ts
  scripts/update-known-events.js
  src/event-handler/on.ts
  src/event-handler/receive.ts
  src/event-handler/remove-listener.ts
  src/generated/event-payloads.ts
  src/generated/get-webhook-payload-type-from-event.ts
  src/generated/webhook-names.ts
  src/index.ts
  src/middleware/get-payload.ts
  src/middleware/middleware.ts
  src/middleware/verify-and-receive.ts
  src/types.ts
  test/fixtures/index.ts
  test/fixtures/push-payload.json
  test/integration/event-handler-test.ts
  test/integration/server-test.ts
  test/typescript-validate.ts
  tsconfig.json
Labels: feature, typescript

#422 fix: type the return of `createEventHandler`
  src/event-handler/index.ts
Labels: bug

#427 refactor(webhooks-class): rename variables in Webhooks generic class
  src/index.ts
Labels: maintenance, typescript

#416 docs: add the information on how to remove the `onAny()` & `onError()` event handlers
  README.md
Labels: bug, documentation

#430 chore(renovate): ignore `@octokit/webhooks-definitions`
  package.json
Labels: maintenance

#435 fix(typescript): resolve correct value for `BaseWebhookEvent#name`
  src/types.ts
  test/typescript-validate.ts
Labels: bug, typescript

#444 v8.0.0
  .github/ISSUE_TEMPLATE/04_feature_request.md
  README.md
  package.json
  scripts/generate-types.ts
  src/event-handler/index.ts
  src/event-handler/on.ts
  src/event-handler/receive.ts
  src/event-handler/remove-listener.ts
  src/event-handler/wrap-error-handler.ts
  src/generated/event-payloads.ts
  src/generated/get-webhook-payload-type-from-event.ts
  src/generated/webhook-names.ts
  src/index.ts
  src/middleware/middleware.ts
  src/middleware/verify-and-receive.ts
  src/types.ts
  test/integration/event-handler-test.ts
  test/integration/sign-test.ts
  test/typescript-validate.ts
  test/unit/event-handler-on-test.ts
  test/unit/middleware-test.ts
Labels: feature

#456 refactor(typescript): simplify `HandlerFunction` type
  src/types.ts
Labels: feature, typescript

#459 fix(typescript): infer TTransformed from createEventHandler() options
  src/event-handler/index.ts
Labels: bug

#448 fix(docs): Use correct links in subfolder Readme files
  src/event-handler/README.md
  src/middleware/README.md
  src/sign/README.md
  src/verify/README.md
Labels: bug, documentation

#457 feat(logging): add log option
  jest.config.ts
  src/event-handler/index.ts
  src/event-handler/on.ts
  src/index.ts
  src/middleware/index.ts
  src/middleware/middleware.ts
  src/types.ts
  test/integration/middleware-test.ts
  test/unit/event-handler-on-test.ts
  test/unit/event-handler-receive-test.ts
  test/unit/event-handler-remove-listener-test.ts
  test/unit/middleware-test.ts
Labels: feature

#460 refactor(typescript): simplify TransformMethod type
  src/event-handler/index.ts
  src/event-handler/receive.ts
  src/index.ts
  src/middleware/index.ts
  src/types.ts
Labels: bug, typescript

#462 refactor: move `createLogger` into its own file
  src/createLogger.ts
  src/event-handler/index.ts
  src/index.ts
  src/middleware/index.ts
  src/types.ts
  test/unit/createLogger-test.ts
Labels: maintenance

#458 feat(typescript): compile-time missing options error
  src/event-handler/index.ts
  src/index.ts
  test/integration/server-test.ts
  test/typescript-validate.ts
Labels: feature, typescript

#469 ci: fix `@octokit/webhooks-definitions` updater
  .github/workflows/update.yml
Labels: maintenance

#467 docs: update broken delivery headers link
  src/middleware/get-missing-headers.ts
Labels: bug, documentation

#472 ci(update): await `@octokit/webhooks-definitions` package version to be published to npm before downloading it from the registry
  .github/workflows/update.yml
Labels: maintenance

#473 ci(update): move the install of @octokit/webhooks-definitions to after the wait action
  .github/workflows/update.yml
Labels: maintenance

#465 fix(typescript): compile-time invalid argument errors
  test/integration/server-test.ts
  test/integration/sign-test.ts
  test/unit/event-handler-on-test.ts
Labels: maintenance
