Repository octokit/webhooks.js, pull requests merged in 2021-09, with the labels that each got.

#625 docs(README): fix link to webhook docs
  README.md
  scripts/generate-types.ts
Labels: bug, documentation

#626 feat: export emitterEventNames
  README.md
  src/index.ts
  test/integration/smoke-test.ts
Labels: feature

#611 fix: handle invalid URL
  src/middleware/node/middleware.ts
  test/integration/node-middleware.test.ts
Labels: bug
