Repository octokit/webhooks.js, pull requests merged in 2023-01, with the labels that each got.

#790 feat: deprecate `onUnhandledRequest` and accepting object payloads for for `webhooks.verify()` and `webhooks.verifyAndReceive()`
  README.md
  src/index.ts
  src/middleware/node/index.ts
  src/middleware/node/types.ts
  src/to-normalized-json-string.ts
  src/types.ts
  test/integration/node-middleware.test.ts
  test/integration/webhooks.test.ts
  test/unit/deprecation.test.ts
Labels: Type: Maintenance

#793 feat: only accept string payloads for `webhooks.verify()` and `webhooks.verifyAndReceive()`
  src/index.ts
  src/middleware/node/get-payload.ts
  src/middleware/node/middleware.ts
  src/types.ts
  src/verify-and-receive.ts
  src/verify.ts
  test/integration/node-middleware.test.ts
  test/integration/webhooks.test.ts
  test/typescript-validate.ts
  test/unit/deprecation.test.ts
Labels: Type: Feature

#795 fix: return more helpful error when `Content-Type` header is not `application/json`
  src/middleware/node/middleware.ts
  test/integration/node-middleware.test.ts
Labels: Type: Feature, Priority: Normal

#798 Default branch rename
  .github/pull_request_template.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
  README.md
  package.json
Labels: Type: Maintenance

#794 feat: only accept string payloads for `webhooks.sign()`
  README.md
  src/index.ts
  src/sign.ts
  src/to-normalized-json-string.ts
  test/integration/webhooks.test.ts
  test/typescript-validate.ts
Labels: Type: Feature, Type: Breaking change

#799 feat(middlware): allow string payloads
  src/middleware/node/get-payload.ts
Labels: Type: Feature

#800 docs: add note about required `strictNullChecks` option
  README.md
Labels: Type: Documentation

#801 fix(logging): change error to warn
  src/index.ts
  src/middleware/node/get-payload.ts
  src/middleware/node/index.ts
  test/unit/deprecation.test.ts
Labels: Type: Bug

#805 fix: handle missing `Content-Type` header with `null` check
  src/middleware/node/middleware.ts
  test/integration/node-middleware.test.ts
Labels: Type: Bug, Priority: Normal
