Repository octokit/webhooks.js, pull requests merged in 2025-02, with the labels that each got.

#1103 fix(deps): bump `@octokit/webhooks-methods`
  package-lock.json
  package.json
Labels: Type: Bug

#1101 fix(types): mark type parameters as optional
  src/event-handler/index.ts
  src/types.ts
Labels: Type: Bug

#1114 fix: add `./types` entrypoint
  scripts/build.mjs
Labels: Type: Bug

#1119 fix(types): explicit return type from web `middleware()`
  src/middleware/web/middleware.ts
Labels: Type: Bug, typescript

#1116 docs: add `createWebMiddleware()` & update `event-handler` to reflect ESM usage
  README.md
  package.json
  src/event-handler/README.md
Labels: Type: Documentation
